### ISSUE TITLE
Using "connect"

### ISSUE THREAD

**Issue by josteph** [dai-shi/redux-in-worker#19]
Is using `connect` from react-redux is supported? I seem to be always getting `undefined` when using `connect`

```
import { connect } from 'react-redux';
import SomeComponent from './SomeComponent';

// state is undefined ?
const mapStateToProps = (state) => ({
  state,
});

export default connect(mapStateToProps, null)(SomeComponent);
```

**Comment by dai-shi** [comment]
This library only depends on `redux` and it doesn't matter how it's used with `react-redux`. (It can even be used without react. One of my trials is [svelte binding](https://github.com/dai-shi/svelte3-redux).)

I'm not sure but can your issue of `undefined` happen with `useSelector` too?

**Comment by josteph** [comment]
Ah I think it happens because the project is using https://github.com/reduxjs/reselect

Is there any example of how to do this with `reselect` ?

**Comment by dai-shi** [comment]
No, but it should be just the same. Again, this is just redux level. You want to use reselect with react-redux, right?

**Comment by josteph** [comment]
You're right it should be the same. There is something else going on here.

I'll try to create an isolated minimal reproduction.

**Comment by josteph** [comment]
This is not an issue with `redux-in-worker` part, sorry for opening an issue before doing deep-diving into the problem.

Some of my helper files within the worker currently have import to `store` to non-worker file, causing unexpected result like infinite worker js request, etc.

I suggest for this to be clearly stated in the docs because it kinda breaks the library pattern.

**Comment by dai-shi** [comment]
I didn't know clearly about such a pitfall.
Would you open a PR for your suggestion?
