### ISSUE TITLE
Does not work with redux-toolkit (createAsyncThunk)

### ISSUE THREAD

**Issue by valerii15298** [dai-shi/redux-in-worker#21]
Hello! Thank you for such a great library. I used redux-toolkit and createAsyncThunk, but there is an error ``Uncaught Error: Actions must be plain objects. Instead, the actual type was: 'function'. You may need to add middleware to your store setup to handle dispatching other values, such as 'redux-thunk' to handle dispatching functions. See https://redux.js.org/tutorials/fundamentals/part-4-store#middleware and https://redux.js.org/tutorials/fundamentals/part-6-async-logic#using-the-redux-thunk-middleware for examples.` Though it is working without redux-in-worker

**Comment by dai-shi** [comment]
So, we can't pass 'function' from main thread to worker thread.
This means we can't use redux-thunk, which means we can't use createAsyncThunk.

Please see my blog post:
https://blog.axlight.com/posts/redux-in-worker-off-main-thread-redux-reducers-and-middleware/
> One of the biggest hurdles in this approach is redux-thunk. redux-thunk takes a function action which is not serializable. It’s the official tool and included in Redux Toolkit too. This implies this approach is not going to be mainstream.
