### ISSUE TITLE
Self is undefined

### ISSUE THREAD

**Issue by don-siu** [dai-shi/redux-in-worker#5]
Where did you define `self`? I received a `ReferenceError` here. 

![image](https://user-images.githubusercontent.com/42818524/88344388-4e8c6180-ccf8-11ea-8ca5-4622c9809f9e.png)

https://github.com/dai-shi/redux-in-worker/blob/51184ec425d75233c64374393d108a89fc234ebe/dist/exposeStore.js#L143

**Comment by dai-shi** [comment]
Hey, `self` is in the global scope of worker. You want to call `exposeStore` in worker files.

https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/self

**Comment by don-siu** [comment]
> Hey, `self` is in the global scope of worker. You want to call `exposeStore` in worker files.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/self

Hey, thanks for your quick reply.

hmmm, I already called exposeStore in the `worker.js` and also tried to bind the worker context with `exposeStore.bind(workerContext, store)` but received 
![image](https://user-images.githubusercontent.com/42818524/88344899-8b0c8d00-ccf9-11ea-992f-b5cfe233a4bf.png)

Is that the CRA issue Surma mentioned before? I don't really know how that will impact. 😥

**Comment by dai-shi** [comment]
hm, I never needed to `bind` worker context.
yeah, CRA doesn't suppoort workers yet. I only tried with webpack's worker-plugin. Have you tried the examples in the repo?

**Comment by don-siu** [comment]
The `createStore` part of my project is nested with another function. Split that part and export the `store` would do the work without that scope error. This issue seems resolved. (of course, there are other errors but unrelated to this)

**Comment by don-siu** [comment]
The last question, is this library still not working with redux `thunk` at the moment so does `comlink` ?

**Comment by dai-shi** [comment]
True. In general, you can't transfer arbitrary functions from main thread to worker thread.
